// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: searchQuery.proto

package normalizerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NormalizerService_GetNormalizedQuery_FullMethodName = "/normalizer.v1.NormalizerService/GetNormalizedQuery"
)

// NormalizerServiceClient is the client API for NormalizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NormalizerServiceClient interface {
	GetNormalizedQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type normalizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNormalizerServiceClient(cc grpc.ClientConnInterface) NormalizerServiceClient {
	return &normalizerServiceClient{cc}
}

func (c *normalizerServiceClient) GetNormalizedQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, NormalizerService_GetNormalizedQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NormalizerServiceServer is the server API for NormalizerService service.
// All implementations must embed UnimplementedNormalizerServiceServer
// for forward compatibility.
type NormalizerServiceServer interface {
	GetNormalizedQuery(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedNormalizerServiceServer()
}

// UnimplementedNormalizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNormalizerServiceServer struct{}

func (UnimplementedNormalizerServiceServer) GetNormalizedQuery(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNormalizedQuery not implemented")
}
func (UnimplementedNormalizerServiceServer) mustEmbedUnimplementedNormalizerServiceServer() {}
func (UnimplementedNormalizerServiceServer) testEmbeddedByValue()                           {}

// UnsafeNormalizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NormalizerServiceServer will
// result in compilation errors.
type UnsafeNormalizerServiceServer interface {
	mustEmbedUnimplementedNormalizerServiceServer()
}

func RegisterNormalizerServiceServer(s grpc.ServiceRegistrar, srv NormalizerServiceServer) {
	// If the following call pancis, it indicates UnimplementedNormalizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NormalizerService_ServiceDesc, srv)
}

func _NormalizerService_GetNormalizedQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalizerServiceServer).GetNormalizedQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalizerService_GetNormalizedQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalizerServiceServer).GetNormalizedQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NormalizerService_ServiceDesc is the grpc.ServiceDesc for NormalizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NormalizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "normalizer.v1.NormalizerService",
	HandlerType: (*NormalizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNormalizedQuery",
			Handler:    _NormalizerService_GetNormalizedQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "searchQuery.proto",
}
