// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: searchQuery.proto

package normalizerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchQuery   string                 `protobuf:"bytes,1,opt,name=searchQuery,proto3" json:"searchQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_searchQuery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchQuery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_searchQuery_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	URL           string                 `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_searchQuery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_searchQuery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_searchQuery_proto_rawDescGZIP(), []int{1}
}

func (x *Source) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type QueryStructure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataEntity    string                 `protobuf:"bytes,1,opt,name=dataEntity,proto3" json:"dataEntity,omitempty"`
	OutputFormat  string                 `protobuf:"bytes,2,opt,name=outputFormat,proto3" json:"outputFormat,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	CountryCode   string                 `protobuf:"bytes,4,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=endDate,proto3" json:"endDate,omitempty"`
	Sources       []*Source              `protobuf:"bytes,7,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStructure) Reset() {
	*x = QueryStructure{}
	mi := &file_searchQuery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStructure) ProtoMessage() {}

func (x *QueryStructure) ProtoReflect() protoreflect.Message {
	mi := &file_searchQuery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStructure.ProtoReflect.Descriptor instead.
func (*QueryStructure) Descriptor() ([]byte, []int) {
	return file_searchQuery_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStructure) GetDataEntity() string {
	if x != nil {
		return x.DataEntity
	}
	return ""
}

func (x *QueryStructure) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *QueryStructure) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *QueryStructure) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *QueryStructure) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *QueryStructure) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *QueryStructure) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

type QueryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NormalizedQuery []*QueryStructure      `protobuf:"bytes,1,rep,name=normalizedQuery,proto3" json:"normalizedQuery,omitempty"`
	Sources         []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	Urls            []string               `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_searchQuery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchQuery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_searchQuery_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetNormalizedQuery() []*QueryStructure {
	if x != nil {
		return x.NormalizedQuery
	}
	return nil
}

func (x *QueryResponse) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *QueryResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_searchQuery_proto protoreflect.FileDescriptor

const file_searchQuery_proto_rawDesc = "" +
	"\n" +
	"\x11searchQuery.proto\x12\rnormalizer.v1\"0\n" +
	"\fQueryRequest\x12 \n" +
	"\vsearchQuery\x18\x01 \x01(\tR\vsearchQuery\"\x1a\n" +
	"\x06Source\x12\x10\n" +
	"\x03URL\x18\x01 \x01(\tR\x03URL\"\xfb\x01\n" +
	"\x0eQueryStructure\x12\x1e\n" +
	"\n" +
	"dataEntity\x18\x01 \x01(\tR\n" +
	"dataEntity\x12\"\n" +
	"\foutputFormat\x18\x02 \x01(\tR\foutputFormat\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12 \n" +
	"\vcountryCode\x18\x04 \x01(\tR\vcountryCode\x12\x1c\n" +
	"\tstartDate\x18\x05 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x06 \x01(\tR\aendDate\x12/\n" +
	"\asources\x18\a \x03(\v2\x15.normalizer.v1.SourceR\asources\"\x86\x01\n" +
	"\rQueryResponse\x12G\n" +
	"\x0fnormalizedQuery\x18\x01 \x03(\v2\x1d.normalizer.v1.QueryStructureR\x0fnormalizedQuery\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\x12\x12\n" +
	"\x04urls\x18\x03 \x03(\tR\x04urls2f\n" +
	"\x11NormalizerService\x12Q\n" +
	"\x12GetNormalizedQuery\x12\x1b.normalizer.v1.QueryRequest\x1a\x1c.normalizer.v1.QueryResponse\"\x00B\x1fZ\x1d/querynormalizer;normalizerpbb\x06proto3"

var (
	file_searchQuery_proto_rawDescOnce sync.Once
	file_searchQuery_proto_rawDescData []byte
)

func file_searchQuery_proto_rawDescGZIP() []byte {
	file_searchQuery_proto_rawDescOnce.Do(func() {
		file_searchQuery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_searchQuery_proto_rawDesc), len(file_searchQuery_proto_rawDesc)))
	})
	return file_searchQuery_proto_rawDescData
}

var file_searchQuery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_searchQuery_proto_goTypes = []any{
	(*QueryRequest)(nil),   // 0: normalizer.v1.QueryRequest
	(*Source)(nil),         // 1: normalizer.v1.Source
	(*QueryStructure)(nil), // 2: normalizer.v1.QueryStructure
	(*QueryResponse)(nil),  // 3: normalizer.v1.QueryResponse
}
var file_searchQuery_proto_depIdxs = []int32{
	1, // 0: normalizer.v1.QueryStructure.sources:type_name -> normalizer.v1.Source
	2, // 1: normalizer.v1.QueryResponse.normalizedQuery:type_name -> normalizer.v1.QueryStructure
	0, // 2: normalizer.v1.NormalizerService.GetNormalizedQuery:input_type -> normalizer.v1.QueryRequest
	3, // 3: normalizer.v1.NormalizerService.GetNormalizedQuery:output_type -> normalizer.v1.QueryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_searchQuery_proto_init() }
func file_searchQuery_proto_init() {
	if File_searchQuery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_searchQuery_proto_rawDesc), len(file_searchQuery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_searchQuery_proto_goTypes,
		DependencyIndexes: file_searchQuery_proto_depIdxs,
		MessageInfos:      file_searchQuery_proto_msgTypes,
	}.Build()
	File_searchQuery_proto = out.File
	file_searchQuery_proto_goTypes = nil
	file_searchQuery_proto_depIdxs = nil
}
