# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: extract.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'extract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rextract.proto\x12\x08metadata\"+\n\x0e\x45xtractRequest\x12\x0c\n\x04html\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"(\n\x0f\x45xtractResponse\x12\x15\n\rjson_response\x18\x01 \x01(\t2K\n\tExtractor\x12>\n\x07\x45xtract\x12\x18.metadata.ExtractRequest\x1a\x19.metadata.ExtractResponseB\x0cZ\n/extractorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n/extractor'
  _globals['_EXTRACTREQUEST']._serialized_start=27
  _globals['_EXTRACTREQUEST']._serialized_end=70
  _globals['_EXTRACTRESPONSE']._serialized_start=72
  _globals['_EXTRACTRESPONSE']._serialized_end=112
  _globals['_EXTRACTOR']._serialized_start=114
  _globals['_EXTRACTOR']._serialized_end=189
# @@protoc_insertion_point(module_scope)
