// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: extract.proto

package extractor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Html          string                 `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_extract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractRequest) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *ExtractRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonResponse  string                 `protobuf:"bytes,1,opt,name=json_response,json=jsonResponse,proto3" json:"json_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_extract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractResponse) GetJsonResponse() string {
	if x != nil {
		return x.JsonResponse
	}
	return ""
}

var File_extract_proto protoreflect.FileDescriptor

const file_extract_proto_rawDesc = "" +
	"\n" +
	"\rextract.proto\x12\bmetadata\"6\n" +
	"\x0eExtractRequest\x12\x12\n" +
	"\x04html\x18\x01 \x01(\tR\x04html\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"6\n" +
	"\x0fExtractResponse\x12#\n" +
	"\rjson_response\x18\x01 \x01(\tR\fjsonResponse2K\n" +
	"\tExtractor\x12>\n" +
	"\aExtract\x12\x18.metadata.ExtractRequest\x1a\x19.metadata.ExtractResponseB\fZ\n" +
	"/extractorb\x06proto3"

var (
	file_extract_proto_rawDescOnce sync.Once
	file_extract_proto_rawDescData []byte
)

func file_extract_proto_rawDescGZIP() []byte {
	file_extract_proto_rawDescOnce.Do(func() {
		file_extract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extract_proto_rawDesc), len(file_extract_proto_rawDesc)))
	})
	return file_extract_proto_rawDescData
}

var file_extract_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extract_proto_goTypes = []any{
	(*ExtractRequest)(nil),  // 0: metadata.ExtractRequest
	(*ExtractResponse)(nil), // 1: metadata.ExtractResponse
}
var file_extract_proto_depIdxs = []int32{
	0, // 0: metadata.Extractor.Extract:input_type -> metadata.ExtractRequest
	1, // 1: metadata.Extractor.Extract:output_type -> metadata.ExtractResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extract_proto_init() }
func file_extract_proto_init() {
	if File_extract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extract_proto_rawDesc), len(file_extract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extract_proto_goTypes,
		DependencyIndexes: file_extract_proto_depIdxs,
		MessageInfos:      file_extract_proto_msgTypes,
	}.Build()
	File_extract_proto = out.File
	file_extract_proto_goTypes = nil
	file_extract_proto_depIdxs = nil
}
