FROM python:3.12-slim AS base
WORKDIR /app
COPY services/nltk_test/requirements.txt /app/
RUN pip install --no-cache-dir -U pip setuptools wheel
RUN pip install --no-cache-dir requirements.txt

COPY proto /proto
RUN python -m grpc_tools.protoc -I /proto \
    --python_out=/generated --grpc_python_out=/generated \
    /proto/*.proto

COPY services/nltk_test /app/app
ENV PYTHONBUFFERED=1
USER 65532:65532
EXPOSE 50051
CMD ["python","-m", "server"]
