# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: searchQuery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'searchQuery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11searchQuery.proto\x12\rnormalizer.v1\"#\n\x0cQueryRequest\x12\x13\n\x0bsearchQuery\x18\x01 \x01(\t\"p\n\x0eQueryStructure\x12\x12\n\ndataEntity\x18\x01 \x01(\t\x12\x14\n\x0coutputFormat\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x11\n\tstartDate\x18\x04 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x05 \x01(\t\"f\n\rQueryResponse\x12\x36\n\x0fnormalizedQuery\x18\x01 \x03(\x0b\x32\x1d.normalizer.v1.QueryStructure\x12\x0f\n\x07sources\x18\x02 \x03(\t\x12\x0c\n\x04urls\x18\x03 \x03(\t2f\n\x11NormalizerService\x12Q\n\x12GetNormalizedQuery\x12\x1b.normalizer.v1.QueryRequest\x1a\x1c.normalizer.v1.QueryResponse\"\x00\x42\x1fZ\x1d/querynormalizer;normalizerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'searchQuery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035/querynormalizer;normalizerpb'
  _globals['_QUERYREQUEST']._serialized_start=36
  _globals['_QUERYREQUEST']._serialized_end=71
  _globals['_QUERYSTRUCTURE']._serialized_start=73
  _globals['_QUERYSTRUCTURE']._serialized_end=185
  _globals['_QUERYRESPONSE']._serialized_start=187
  _globals['_QUERYRESPONSE']._serialized_end=289
  _globals['_NORMALIZERSERVICE']._serialized_start=291
  _globals['_NORMALIZERSERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
